-- 0003_post_tag_position: down
-- Generated by orm; edit freely before applying.

-- drop column post_tags.position
-- WARNING: drops column post_tags.position and its data
ALTER TABLE "post_tags" DROP COLUMN "position";

