[build-system]
requires = ["maturin>=1.5,<2"]
build-backend = "maturin"

[project]
name = "orm-native-postgres"
version = "0.1.0"
requires-python = ">=3.11"
description = "Statically compiled ORM postgres engine"

[tool.maturin]
manifest-path = "../../../bindings/python/Cargo.toml"
python-source = "."
module-name = "orm_native_postgres._native"
no-default-features = true
features = ["pyo3/extension-module", "profile-postgres"]
