-- 0001_initial: down
-- Generated by orm; edit freely before applying.

-- drop constraint posts_author_id_fkey on posts
ALTER TABLE "posts" DROP CONSTRAINT "posts_author_id_fkey";

-- drop constraint comments_post_id_fkey on comments
ALTER TABLE "comments" DROP CONSTRAINT "comments_post_id_fkey";

-- drop constraint comments_author_id_fkey on comments
ALTER TABLE "comments" DROP CONSTRAINT "comments_author_id_fkey";

-- drop table users
-- WARNING: drops table users and all its rows
DROP TABLE "users";

-- drop table posts
-- WARNING: drops table posts and all its rows
DROP TABLE "posts";

-- drop table comments
-- WARNING: drops table comments and all its rows
DROP TABLE "comments";

-- drop extension pg_trgm
-- WARNING: drops extension pg_trgm; other schemas may still use it
DROP EXTENSION IF EXISTS "pg_trgm";
