-- 0001_initial: up
-- Generated by orm; edit freely before applying.

-- create extension pg_trgm
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- create table users
CREATE TABLE "users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" varchar(254) NOT NULL,
    "name" varchar(100) NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "users_email_key" UNIQUE ("email")
);

-- create table posts
CREATE TABLE "posts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "author_id" bigint NOT NULL,
    "title" varchar(200) NOT NULL,
    "body" text NOT NULL,
    "views" integer DEFAULT 0 NOT NULL,
    "published" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "posts_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "posts_views_not_negative" CHECK (views >= 0),
    CONSTRAINT "posts_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- create table comments
CREATE TABLE "comments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "post_id" bigint NOT NULL,
    "author_id" bigint,
    "body" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "comments_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
    CONSTRAINT "comments_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE SET NULL
);

-- create index posts_author_id_idx on posts
CREATE INDEX "posts_author_id_idx" ON "posts" ("author_id");

-- create index posts_author_id_created_at_idx on posts
CREATE INDEX "posts_author_id_created_at_idx" ON "posts" ("author_id", "created_at" DESC) WHERE published;

-- create index posts_title_idx on posts
CREATE INDEX "posts_title_idx" ON "posts" USING gin ("title" gin_trgm_ops);

-- create index comments_post_id_idx on comments
CREATE INDEX "comments_post_id_idx" ON "comments" ("post_id");

-- create index comments_author_id_idx on comments
CREATE INDEX "comments_author_id_idx" ON "comments" ("author_id");
