[package]
name = "orm-python"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
orm-core = { path = "../../core" }
orm-engine = { path = "../../engine" }
orm-cli = { path = "../../cli" }
pyo3 = { version = "0.29", features = ["chrono", "uuid"] }
pyo3-async-runtimes = { version = "0.29", features = ["tokio-runtime"] }
sea-query = { version = "1.0", features = ["backend-postgres", "with-chrono", "with-json", "with-uuid", "with-bigdecimal", "postgres-array", "thread-safe", "hashable-value"] }
serde_json = "1"
chrono = "0.4"
uuid = "1"
bigdecimal = "0.4"

[features]
composition = ["orm-engine/composition", "orm-core/composition"]
file-storage = ["orm-engine/file-storage", "orm-core/file-storage"]
