-- 0002_relations_enums_decimals: down
-- Generated by orm; edit freely before applying.

-- drop constraint profiles_user_id_fkey on profiles
ALTER TABLE "profiles" DROP CONSTRAINT "profiles_user_id_fkey";

-- drop constraint post_tags_post_id_fkey on post_tags
ALTER TABLE "post_tags" DROP CONSTRAINT "post_tags_post_id_fkey";

-- drop constraint post_tags_tag_id_fkey on post_tags
ALTER TABLE "post_tags" DROP CONSTRAINT "post_tags_tag_id_fkey";

-- drop table profiles
-- WARNING: drops table profiles and all its rows
DROP TABLE "profiles";

-- drop table tags
-- WARNING: drops table tags and all its rows
DROP TABLE "tags";

-- drop table post_tags
-- WARNING: drops table post_tags and all its rows
DROP TABLE "post_tags";

-- drop enum role
DROP TYPE "role";

