-- 0002_relations_enums_decimals: up
-- Generated by orm; edit freely before applying.

-- create enum role
CREATE TYPE "role" AS ENUM ('member', 'editor', 'admin');

-- create table profiles
CREATE TABLE "profiles" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" bigint NOT NULL,
    "role" "role" DEFAULT 'member' NOT NULL,
    "balance" numeric(12, 2) DEFAULT 0 NOT NULL,
    "links" text[] DEFAULT '{}'::text[] NOT NULL,
    CONSTRAINT "profiles_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "profiles_user_id_key" UNIQUE ("user_id"),
    CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- create table tags
CREATE TABLE "tags" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" varchar(50) NOT NULL,
    "priority" integer DEFAULT 2 NOT NULL,
    CONSTRAINT "tags_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "tags_name_key" UNIQUE ("name"),
    CONSTRAINT "tags_priority_enum_check" CHECK ("priority" IN (1, 2, 3))
);

-- create table post_tags
CREATE TABLE "post_tags" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "post_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL,
    CONSTRAINT "post_tags_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "post_tags_post_id_tag_id_key" UNIQUE ("post_id", "tag_id"),
    CONSTRAINT "post_tags_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
    CONSTRAINT "post_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE
);

-- create index post_tags_tag_id_idx on post_tags
CREATE INDEX "post_tags_tag_id_idx" ON "post_tags" ("tag_id");

