[package]
name = "orm-node"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "orm_node"
crate-type = ["cdylib"]

[dependencies]
orm-core = { path = "../../core" }
orm-engine = { path = "../../engine" }
orm-cli = { path = "../../cli" }
napi = { version = "3", default-features = false, features = ["napi8", "tokio_rt", "serde-json"] }
napi-derive = "3"
sea-query = { version = "1.0", features = ["backend-postgres", "with-chrono", "with-json", "with-uuid", "with-bigdecimal", "postgres-array", "thread-safe", "hashable-value"] }
serde_json = "1"
chrono = "0.4"
uuid = "1"
bigdecimal = "0.4"

[build-dependencies]
napi-build = "2"

[features]
composition = ["orm-engine/composition", "orm-core/composition"]
file-storage = ["orm-engine/file-storage", "orm-core/file-storage"]
