"""Native engine (Rust, PyO3). Internal: use the ``orm`` package API instead."""

from collections.abc import Awaitable
from pathlib import Path
from typing import Any, final

@final
class _Default: ...

DEFAULT: _Default

class DatabaseError(Exception): ...
class IntegrityError(DatabaseError): ...
class LockNotAvailable(DatabaseError): ...
class QueryError(ValueError): ...
class SchemaError(ValueError): ...
class MigrationError(Exception): ...

def prepare_schema(schema_json: str, context_json: str | None = None) -> str: ...
def native_artifact() -> str: ...

def compile_schema(source: str, path: str | None = None) -> str: ...
def compile_schema_file(path: str) -> str: ...
def generate_python(path: str) -> tuple[str, str]: ...
def cli(argv: list[str]) -> int: ...
def list_migrations(dir: str) -> list[tuple[str, Path]]: ...
def find_migration(dir: str, name: str) -> tuple[str, Path]: ...

@final
class Schema:
    def __init__(self, schema_json: str, classes: dict[str, type] | None = None) -> None: ...
    def validate_insert(self, model: str, fields: list[str], rows: list[list[Any]]) -> None: ...
    def unique_row_update(self, op_json: str, params: list[Any]) -> bool: ...
    def sql(self, op_json: str, params: list[Any]) -> str: ...
    def update_many_sql(
        self,
        model: str,
        fields: list[str],
        rows: list[list[Any]],
        filters_json: str = "[]",
        params: list[Any] = ...,
        batch_size: int | None = None,
        disable: list[str] = ...,
    ) -> list[str]: ...
    def ddl(self) -> list[str]: ...
    def snapshot(self) -> str: ...
    def migration(self, previous: str | None = None) -> str: ...
    def plan_migration(self, dir: str) -> str: ...
    def make_migration(self, dir: str, name: str | None = None, empty: bool = False) -> str | None: ...

@final
class Transaction:
    def commit(self) -> Awaitable[None]: ...
    def rollback(self) -> Awaitable[None]: ...

@final
class Engine:
    def run(
        self,
        op_json: str,
        params: list[Any],
        tx: Transaction | None = None,
        row_cls: type | None = None,
        db: Any = None,
    ) -> Awaitable[Any]: ...
    def insert(
        self,
        model: str,
        fields: list[str],
        rows: list[list[Any]],
        conflict: list[str] | None = None,
        update: list[str] | None = None,
        set: str | None = None,
        params: list[Any] = ...,
        tx: Transaction | None = None,
        db: Any = None,
    ) -> Awaitable[list[Any]]: ...
    def attach(self, model: str, parent_id: Any, fields: list[str], rows: list[list[Any]], tx: Transaction | None = None, db: Any = None) -> Awaitable[list[Any]]: ...
    def update_many(
        self,
        model: str,
        fields: list[str],
        rows: list[list[Any]],
        filters_json: str,
        params: list[Any],
        returning: bool = False,
        batch_size: int | None = None,
        tx: Transaction | None = None,
        db: Any = None,
        without_defaults: bool = False,
    ) -> Awaitable[Any]: ...
    def begin(self, tx: Transaction | None = None) -> Awaitable[Transaction]: ...
    def advisory_lock(self, key: int, name: bytes | None, exclusive: bool, nowait: bool, tx: Transaction) -> Awaitable[bool]: ...
    def execute(self, sql: str, tx: Transaction | None = None) -> Awaitable[int]: ...
    def execute_script(self, statements: list[str], tx: Transaction | None = None) -> Awaitable[None]: ...
    def fetch_text(self, sql: str, tx: Transaction | None = None) -> Awaitable[list[tuple[str | None, ...]]]: ...
    def create_tables(self) -> Awaitable[None]: ...
    def drop_tables(self) -> Awaitable[None]: ...
    def migration_status(self, dir: str) -> Awaitable[list[tuple[str, bool, str | None]]]: ...
    def migrate_up(self, dir: str, target: str | None = None) -> Awaitable[list[str]]: ...
    def migrate_down(self, dir: str, steps: int = 1, target: str | None = None) -> Awaitable[list[str]]: ...
    def close(self) -> Awaitable[None]: ...

def connect(
    url: str, schema: Schema, max_connections: int = 10, disable: list[str] = ...
) -> Awaitable[Engine]: ...

# Exact statically compiled packaging metadata, JSON ABI 1.
def profile_metadata() -> str: ...
