"""Native engine (Rust, PyO3). Internal: use the ``orm`` package API instead."""

from collections.abc import Awaitable
from typing import Any, final

@final
class _Default: ...

DEFAULT: _Default

class DatabaseError(Exception): ...
class IntegrityError(DatabaseError): ...
class QueryError(ValueError): ...

@final
class Schema:
    def __init__(self, schema_json: str) -> None: ...
    def sql(self, op_json: str, params: list[Any]) -> str: ...
    def ddl(self) -> list[str]: ...
    def snapshot(self) -> str: ...
    def migration(self, previous: str | None = None) -> str: ...

@final
class Transaction:
    def commit(self) -> Awaitable[None]: ...
    def rollback(self) -> Awaitable[None]: ...

@final
class Engine:
    def run(self, op_json: str, params: list[Any], tx: Transaction | None = None) -> Awaitable[Any]: ...
    def insert(
        self,
        model: str,
        fields: list[str],
        rows: list[list[Any]],
        conflict: list[str] | None = None,
        update: list[str] | None = None,
        tx: Transaction | None = None,
    ) -> Awaitable[list[tuple[Any, ...]]]: ...
    def begin(self, tx: Transaction | None = None) -> Awaitable[Transaction]: ...
    def execute(self, sql: str, tx: Transaction | None = None) -> Awaitable[int]: ...
    def execute_script(self, statements: list[str], tx: Transaction | None = None) -> Awaitable[None]: ...
    def fetch_text(self, sql: str, tx: Transaction | None = None) -> Awaitable[list[tuple[str | None, ...]]]: ...
    def create_tables(self) -> Awaitable[None]: ...
    def drop_tables(self) -> Awaitable[None]: ...
    def close(self) -> Awaitable[None]: ...

def connect(url: str, schema: Schema, max_connections: int = 10) -> Awaitable[Engine]: ...
