-- A database written by hand the way Django and a few raw migrations leave one:
-- the input of the `orm pull` tests (tests/test_pull.py, js/test/pull.test.ts).
CREATE TYPE "shop_status" AS ENUM ('active', 'paused', 'closed');
COMMENT ON TYPE "shop_status" IS 'shop lifecycle';

CREATE FUNCTION set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE account_shop SET _updated_at = now() WHERE id IN (SELECT id FROM new_rows);
    RETURN NULL;
END;
$$;

CREATE FUNCTION slugify(value text) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT lower(value) $$;

CREATE TABLE "account_shop" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "domain" varchar(255) NOT NULL CONSTRAINT "account_shop_domain_9a1b2c3d_uniq" UNIQUE,
    "status" shop_status NOT NULL DEFAULT 'active',
    "plan" varchar(20) NOT NULL DEFAULT 'free' CONSTRAINT "account_shop_plan_check" CHECK ("plan" IN ('free', 'pro')),
    "settings" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "token" uuid NOT NULL DEFAULT gen_random_uuid(),
    "balance" numeric(12, 2) NOT NULL DEFAULT 0,
    "rank" integer NOT NULL DEFAULT -1,
    "tags" text[] NOT NULL DEFAULT '{}',
    "_created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "_updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    "_deleted_at" timestamp with time zone NULL
);
COMMENT ON TABLE "account_shop" IS 'one row per installed shop';
COMMENT ON COLUMN "account_shop"."domain" IS 'myshopify domain';
CREATE INDEX "account_shop_domain_9a1b2c3d_like" ON "account_shop" ("domain" varchar_pattern_ops);
CREATE INDEX "account_shop_live_idx" ON "account_shop" (lower("domain") DESC NULLS LAST) INCLUDE ("plan") WITH (fillfactor = 70) WHERE "_deleted_at" IS NULL;

CREATE TABLE "bundles_bundle" (
    "id" serial NOT NULL PRIMARY KEY,
    "shop_id" bigint NOT NULL,
    "parent_id" integer NULL,
    "title" varchar(200) NOT NULL,
    "position" smallint NOT NULL DEFAULT 0,
    "_deleted_at" timestamp with time zone NULL,
    CONSTRAINT "bundles_bundle_position_check" CHECK ("position" >= 0)
);
ALTER TABLE "bundles_bundle" ADD CONSTRAINT "bundles_bundle_shop_id_8f3e_fk_account_shop_id"
    FOREIGN KEY ("shop_id") REFERENCES "account_shop" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "bundles_bundle" ADD CONSTRAINT "bundles_bundle_parent_id_77aa_fk_bundles_bundle_id"
    FOREIGN KEY ("parent_id") REFERENCES "bundles_bundle" ("id") ON DELETE CASCADE;
CREATE INDEX "bundles_bundle_shop_id_8f3e" ON "bundles_bundle" ("shop_id");
CREATE UNIQUE INDEX "bundles_bundle_live_title" ON "bundles_bundle" ("shop_id", "title") WHERE "_deleted_at" IS NULL;

CREATE TABLE "bundles_slot" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "bundle_id" integer NOT NULL UNIQUE REFERENCES "bundles_bundle" ("id"),
    "during" tstzrange NULL
);

CREATE TABLE "bundles_tag" ("bundle_id" integer NOT NULL, "tag" text NOT NULL, PRIMARY KEY ("bundle_id", "tag"));

CREATE TRIGGER "account_shop_updated_at" AFTER UPDATE ON "account_shop"
    REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT WHEN (pg_trigger_depth() < 1) EXECUTE FUNCTION set_updated_at();
CREATE RULE "bundles_bundle_soft_delete" AS ON DELETE TO "bundles_bundle"
    WHERE OLD."_deleted_at" IS NULL DO INSTEAD UPDATE "bundles_bundle" SET "_deleted_at" = now() WHERE id = OLD.id;
CREATE VIEW "live_bundles" AS SELECT * FROM "bundles_bundle" WHERE "_deleted_at" IS NULL;
