//! The migrations directory: one folder per migration.
//!
//! ```text
//! migrations/
//!     0001_initial/
//!         up.sql          forward DDL, a comment per step (and warnings)
//!         down.sql        reverse DDL
//!         snapshot.json   the database schema after up.sql
//! ```
//!
//! Generating the next migration diffs the schema against the newest snapshot, so it
//! needs no database. Applying migrations is the bindings' job (they own connections).

use std::path::{Path, PathBuf};

use super::{plan, DbSchema, MigrationPlan, Step};
use crate::schema::{Result, Schema};

#[derive(Debug, Clone)]
pub struct MigrationFolder {
    pub name: String,
    pub path: PathBuf,
}

fn io(path: &Path, e: std::io::Error) -> String {
    format!("{}: {e}", path.display())
}

fn numbered(name: &str) -> bool {
    name.len() > 5 && name[..4].bytes().all(|b| b.is_ascii_digit()) && name.as_bytes()[4] == b'_'
}

/// Migrations in order. Two folders with the same number are an error (two branches
/// each added one): renumber one and regenerate it.
pub fn list(dir: &Path) -> Result<Vec<MigrationFolder>> {
    if !dir.is_dir() {
        return Ok(vec![]);
    }
    let mut out = vec![];
    for entry in std::fs::read_dir(dir).map_err(|e| io(dir, e))? {
        let entry = entry.map_err(|e| io(dir, e))?;
        let name = entry.file_name().to_string_lossy().into_owned();
        if entry.path().join("up.sql").is_file() && numbered(&name) {
            out.push(MigrationFolder { name, path: entry.path() });
        }
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    for w in out.windows(2) {
        if w[0].name[..4] == w[1].name[..4] {
            return Err(format!("migrations {} and {} share a number; renumber one", w[0].name, w[1].name));
        }
    }
    Ok(out)
}

pub fn find(dir: &Path, name: &str) -> Result<MigrationFolder> {
    let padded = format!("{:0>4}", name);
    list(dir)?
        .into_iter()
        .find(|m| m.name == name || m.name[..4] == padded)
        .ok_or_else(|| format!("no migration {name:?} in {}", dir.display()))
}

pub fn latest_snapshot(dir: &Path) -> Result<DbSchema> {
    match list(dir)?.last() {
        None => Ok(DbSchema::default()),
        Some(m) => {
            let p = m.path.join("snapshot.json");
            super::parse_snapshot(&std::fs::read_to_string(&p).map_err(|e| io(&p, e))?)
                .map_err(|e| format!("{}: {e}", p.display()))
        }
    }
}

/// What the next migration would contain.
pub fn next(dir: &Path, schema: &Schema) -> Result<MigrationPlan> {
    plan(schema, &latest_snapshot(dir)?)
}

pub fn render(steps: &[Step], title: &str) -> String {
    let mut out = format!("-- {title}\n-- Generated by orm; edit freely before applying.\n\n");
    for s in steps {
        out.push_str(&format!("-- {}\n", s.summary));
        if let Some(w) = &s.warning {
            out.push_str(&format!("-- WARNING: {w}\n"));
        }
        out.push_str(s.sql.trim_end());
        out.push_str(";\n\n");
    }
    out
}

fn slug(text: &str) -> String {
    let mut s = String::new();
    for c in text.to_lowercase().chars() {
        if c.is_ascii_alphanumeric() {
            s.push(c);
        } else if !s.ends_with('_') {
            s.push('_');
        }
    }
    let s: String = s.trim_matches('_').chars().take(40).collect();
    let s = s.trim_end_matches('_').to_owned();
    if s.is_empty() {
        "auto".into()
    } else {
        s
    }
}

/// Writes the next migration. Returns `None` when the schema is unchanged (unless
/// `empty`, which writes one anyway for hand-written SQL).
pub fn make(dir: &Path, schema: &Schema, name: Option<&str>, empty: bool) -> Result<Option<(MigrationFolder, MigrationPlan)>> {
    let plan = next(dir, schema)?;
    if plan.up.is_empty() && !empty {
        return Ok(None);
    }
    let existing = list(dir)?;
    let number = match existing.last() {
        Some(m) => m.name[..4].parse::<u32>().unwrap_or(0) + 1,
        None => 1,
    };
    let label = match name {
        Some(n) => slug(n),
        None if existing.is_empty() => "initial".into(),
        None => plan.up.first().map(|s| slug(&s.summary)).unwrap_or_else(|| "manual".into()),
    };
    let folder = format!("{number:04}_{label}");
    let path = dir.join(&folder);
    std::fs::create_dir_all(&path).map_err(|e| io(&path, e))?;
    let write = |file: &str, text: String| std::fs::write(path.join(file), text).map_err(|e| io(&path.join(file), e));
    write("up.sql", render(&plan.up, &format!("{folder}: up")))?;
    write("down.sql", render(&plan.down, &format!("{folder}: down")))?;
    let snapshot = serde_json::to_string_pretty(&plan.snapshot).map_err(|e| e.to_string())?;
    write("snapshot.json", snapshot + "\n")?;
    Ok(Some((MigrationFolder { name: folder, path }, plan)))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slugs() {
        assert_eq!(slug("create table users"), "create_table_users");
        assert_eq!(slug("  !!"), "auto");
        assert_eq!(slug("Add bookings & rooms"), "add_bookings_rooms");
    }
}
