//! Renders migration operations as PostgreSQL DDL.

use super::diff::{Constraint, Op};
use super::model::{
    quote_literal, Column, Exclusion, ForeignKey, Function, Index, IndexKey, PrimaryKey, Trigger, Unique,
};
use crate::ir::{Deferrable, ForEach, Nulls, OnDelete, TriggerEvent, TriggerTiming};

pub fn ident(name: &str) -> String {
    format!("\"{}\"", name.replace('"', "\"\""))
}

fn idents(names: &[String]) -> String {
    names.iter().map(|n| ident(n)).collect::<Vec<_>>().join(", ")
}

fn action(a: OnDelete) -> &'static str {
    match a {
        OnDelete::Cascade => "CASCADE",
        OnDelete::SetNull => "SET NULL",
        OnDelete::SetDefault => "SET DEFAULT",
        OnDelete::Restrict => "RESTRICT",
        OnDelete::NoAction => "NO ACTION",
    }
}

fn deferrable(d: Option<Deferrable>) -> &'static str {
    match d {
        None => "",
        Some(Deferrable::Immediate) => " DEFERRABLE INITIALLY IMMEDIATE",
        Some(Deferrable::Deferred) => " DEFERRABLE INITIALLY DEFERRED",
    }
}

fn column_def(c: &Column) -> String {
    let mut s = format!("{} {}", ident(&c.name), c.ty);
    if c.identity {
        s.push_str(" GENERATED BY DEFAULT AS IDENTITY");
    }
    if let Some(d) = &c.default {
        s.push_str(&format!(" DEFAULT {d}"));
    }
    if !c.nullable {
        s.push_str(" NOT NULL");
    }
    s
}

fn key(k: &IndexKey) -> String {
    let mut s = match (&k.column, &k.expr) {
        (Some(c), _) => ident(c),
        (None, Some(e)) => format!("({e})"),
        (None, None) => String::new(),
    };
    if let Some(c) = &k.collation {
        s.push_str(&format!(" COLLATE {}", ident(c)));
    }
    if let Some(op) = &k.opclass {
        s.push_str(&format!(" {op}"));
    }
    if k.desc {
        s.push_str(" DESC");
    }
    match k.nulls {
        Some(Nulls::First) => s.push_str(" NULLS FIRST"),
        Some(Nulls::Last) => s.push_str(" NULLS LAST"),
        None => {}
    }
    s
}

fn pk_def(pk: &PrimaryKey) -> String {
    format!("CONSTRAINT {} PRIMARY KEY ({})", ident(&pk.name), idents(&pk.columns))
}

fn unique_def(u: &Unique) -> String {
    format!(
        "CONSTRAINT {} UNIQUE{} ({}){}",
        ident(&u.name),
        if u.nulls_not_distinct { " NULLS NOT DISTINCT" } else { "" },
        idents(&u.columns),
        deferrable(u.deferrable)
    )
}

fn exclusion_def(e: &Exclusion) -> String {
    let elements =
        e.elements.iter().map(|el| format!("{} WITH {}", key(&el.key), el.operator)).collect::<Vec<_>>().join(", ");
    let mut s = format!("CONSTRAINT {} EXCLUDE USING {} ({elements})", ident(&e.name), e.method);
    if let Some(w) = &e.where_ {
        s.push_str(&format!(" WHERE ({w})"));
    }
    s.push_str(deferrable(e.deferrable));
    s
}

fn fk_def(fk: &ForeignKey) -> String {
    let mut s = format!(
        "CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({})",
        ident(&fk.name),
        idents(&fk.columns),
        ident(&fk.ref_table),
        idents(&fk.ref_columns)
    );
    if let Some(a) = fk.on_delete {
        s.push_str(&format!(" ON DELETE {}", action(a)));
    }
    if let Some(a) = fk.on_update {
        s.push_str(&format!(" ON UPDATE {}", action(a)));
    }
    s.push_str(deferrable(fk.deferrable));
    s
}

fn constraint_def(c: &Constraint) -> String {
    match c {
        Constraint::PrimaryKey(pk) => pk_def(pk),
        Constraint::Unique(u) => unique_def(u),
        Constraint::Check(c) => format!("CONSTRAINT {} CHECK ({})", ident(&c.name), c.expr),
        Constraint::Exclusion(e) => exclusion_def(e),
        Constraint::ForeignKey(fk) => fk_def(fk),
    }
}

fn index_def(table: &str, ix: &Index, idempotent: bool) -> String {
    let mut s = format!(
        "CREATE {}INDEX {}{} ON {}",
        if ix.unique { "UNIQUE " } else { "" },
        if idempotent { "IF NOT EXISTS " } else { "" },
        ident(&ix.name),
        ident(table)
    );
    if let Some(m) = &ix.method {
        s.push_str(&format!(" USING {m}"));
    }
    s.push_str(&format!(" ({})", ix.keys.iter().map(key).collect::<Vec<_>>().join(", ")));
    if !ix.include.is_empty() {
        s.push_str(&format!(" INCLUDE ({})", idents(&ix.include)));
    }
    if ix.nulls_not_distinct {
        s.push_str(" NULLS NOT DISTINCT");
    }
    if !ix.with.is_empty() {
        let params = ix.with.iter().map(|(k, v)| format!("{k} = {v}")).collect::<Vec<_>>().join(", ");
        s.push_str(&format!(" WITH ({params})"));
    }
    if let Some(w) = &ix.where_ {
        s.push_str(&format!(" WHERE {w}"));
    }
    s
}

/// A dollar-quote tag that doesn't occur in `body`.
fn dollar_quote(body: &str) -> String {
    let mut tag = "$orm$".to_owned();
    let mut i = 0;
    while body.contains(&tag) {
        i += 1;
        tag = format!("$orm{i}$");
    }
    format!("{tag}\n{body}\n{tag}")
}

fn function_sig(f: &Function) -> String {
    format!("{}({})", ident(&f.name), f.args)
}

fn function_def(f: &Function) -> String {
    let mut s = format!("CREATE OR REPLACE FUNCTION {} RETURNS {} LANGUAGE {}", function_sig(f), f.returns, f.language);
    if let Some(v) = &f.volatility {
        s.push_str(&format!(" {}", v.to_ascii_uppercase()));
    }
    if f.security_definer {
        s.push_str(" SECURITY DEFINER");
    }
    s.push_str(&format!(" AS {}", dollar_quote(&f.body)));
    s
}

fn trigger_def(table: &str, t: &Trigger, idempotent: bool) -> String {
    let timing = match t.timing {
        TriggerTiming::Before => "BEFORE",
        TriggerTiming::After => "AFTER",
        TriggerTiming::InsteadOf => "INSTEAD OF",
    };
    let events = t
        .events
        .iter()
        .map(|e| match e {
            TriggerEvent::Insert => "INSERT".to_owned(),
            TriggerEvent::Update if !t.update_of.is_empty() => format!("UPDATE OF {}", idents(&t.update_of)),
            TriggerEvent::Update => "UPDATE".to_owned(),
            TriggerEvent::Delete => "DELETE".to_owned(),
            TriggerEvent::Truncate => "TRUNCATE".to_owned(),
        })
        .collect::<Vec<_>>()
        .join(" OR ");
    let mut s = format!(
        "CREATE {}TRIGGER {} {timing} {events} ON {} FOR EACH {}",
        if idempotent { "OR REPLACE " } else { "" },
        ident(&t.name),
        ident(table),
        match t.for_each {
            ForEach::Row => "ROW",
            ForEach::Statement => "STATEMENT",
        }
    );
    if let Some(w) = &t.when {
        s.push_str(&format!(" WHEN ({w})"));
    }
    let args = t.args.iter().map(|a| quote_literal(a)).collect::<Vec<_>>().join(", ");
    s.push_str(&format!(" EXECUTE FUNCTION {}({args})", ident(&t.function)));
    s
}

fn comment(c: &Option<String>) -> String {
    c.as_deref().map(quote_literal).unwrap_or_else(|| "NULL".into())
}

/// SQL for one operation. `idempotent` renders `IF NOT EXISTS` / `OR REPLACE` forms
/// where Postgres has them (used by `create_tables`).
pub fn render(op: &Op, idempotent: bool) -> String {
    let alter = |t: &str| format!("ALTER TABLE {}", ident(t));
    match op {
        Op::CreateExtension(e) => {
            let mut s = format!("CREATE EXTENSION IF NOT EXISTS {}", ident(&e.name));
            if let Some(schema) = &e.schema {
                s.push_str(&format!(" SCHEMA {}", ident(schema)));
            }
            if let Some(v) = &e.version {
                s.push_str(&format!(" VERSION {}", quote_literal(v)));
            }
            s
        }
        Op::DropExtension(e) => format!("DROP EXTENSION IF EXISTS {}", ident(&e.name)),
        Op::CreateFunction(f) => function_def(f),
        Op::DropFunction(f) => format!("DROP FUNCTION {}", function_sig(f)),
        Op::CreateTable { table, foreign_keys } => {
            let mut lines: Vec<String> = table.columns.iter().map(column_def).collect();
            lines.extend(table.primary_key.iter().map(pk_def));
            lines.extend(table.uniques.iter().map(unique_def));
            lines.extend(table.checks.iter().map(|c| format!("CONSTRAINT {} CHECK ({})", ident(&c.name), c.expr)));
            lines.extend(table.exclusions.iter().map(exclusion_def));
            lines.extend(foreign_keys.iter().map(fk_def));
            format!(
                "CREATE TABLE {}{} (\n    {}\n)",
                if idempotent { "IF NOT EXISTS " } else { "" },
                ident(&table.name),
                lines.join(",\n    ")
            )
        }
        Op::DropTable { table } => format!("DROP TABLE {}", ident(table)),
        Op::RenameTable { from, to } => format!("{} RENAME TO {}", alter(from), ident(to)),
        Op::RenameColumn { table, from, to } => {
            format!("{} RENAME COLUMN {} TO {}", alter(table), ident(from), ident(to))
        }
        Op::AddColumn { table, column } => format!("{} ADD COLUMN {}", alter(table), column_def(column)),
        Op::DropColumn { table, column } => format!("{} DROP COLUMN {}", alter(table), ident(column)),
        Op::AlterColumnType { table, column, to, .. } => {
            let c = ident(column);
            format!("{} ALTER COLUMN {c} TYPE {to} USING {c}::{to}", alter(table))
        }
        Op::SetNotNull { table, column } => format!("{} ALTER COLUMN {} SET NOT NULL", alter(table), ident(column)),
        Op::DropNotNull { table, column } => format!("{} ALTER COLUMN {} DROP NOT NULL", alter(table), ident(column)),
        Op::SetDefault { table, column, default } => {
            format!("{} ALTER COLUMN {} SET DEFAULT {default}", alter(table), ident(column))
        }
        Op::DropDefault { table, column } => format!("{} ALTER COLUMN {} DROP DEFAULT", alter(table), ident(column)),
        Op::AddIdentity { table, column } => {
            format!("{} ALTER COLUMN {} ADD GENERATED BY DEFAULT AS IDENTITY", alter(table), ident(column))
        }
        Op::DropIdentity { table, column } => format!("{} ALTER COLUMN {} DROP IDENTITY", alter(table), ident(column)),
        Op::AddConstraint { table, constraint } => format!("{} ADD {}", alter(table), constraint_def(constraint)),
        Op::DropConstraint { table, name } => format!("{} DROP CONSTRAINT {}", alter(table), ident(name)),
        Op::RenameConstraint { table, from, to } => {
            format!("{} RENAME CONSTRAINT {} TO {}", alter(table), ident(from), ident(to))
        }
        Op::CreateIndex { table, index } => index_def(table, index, idempotent),
        Op::DropIndex { name } => format!("DROP INDEX {}", ident(name)),
        Op::RenameIndex { from, to } => format!("ALTER INDEX {} RENAME TO {}", ident(from), ident(to)),
        Op::CreateTrigger { table, trigger } => trigger_def(table, trigger, idempotent),
        Op::DropTrigger { table, name } => format!("DROP TRIGGER {} ON {}", ident(name), ident(table)),
        Op::CommentOnTable { table, comment: c } => format!("COMMENT ON TABLE {} IS {}", ident(table), comment(c)),
        Op::CommentOnColumn { table, column, comment: c } => {
            format!("COMMENT ON COLUMN {}.{} IS {}", ident(table), ident(column), comment(c))
        }
    }
}

/// One-line description for migration files.
pub fn summary(op: &Op) -> String {
    match op {
        Op::CreateExtension(e) => format!("create extension {}", e.name),
        Op::DropExtension(e) => format!("drop extension {}", e.name),
        Op::CreateFunction(f) => format!("create or replace function {}({})", f.name, f.args),
        Op::DropFunction(f) => format!("drop function {}({})", f.name, f.args),
        Op::CreateTable { table, .. } => format!("create table {}", table.name),
        Op::DropTable { table } => format!("drop table {table}"),
        Op::RenameTable { from, to } => format!("rename table {from} to {to}"),
        Op::RenameColumn { table, from, to } => format!("rename column {table}.{from} to {to}"),
        Op::AddColumn { table, column } => format!("add column {table}.{}", column.name),
        Op::DropColumn { table, column } => format!("drop column {table}.{column}"),
        Op::AlterColumnType { table, column, to, .. } => format!("change type of {table}.{column} to {to}"),
        Op::SetNotNull { table, column } => format!("make {table}.{column} NOT NULL"),
        Op::DropNotNull { table, column } => format!("make {table}.{column} nullable"),
        Op::SetDefault { table, column, .. } => format!("set default of {table}.{column}"),
        Op::DropDefault { table, column } => format!("drop default of {table}.{column}"),
        Op::AddIdentity { table, column } => format!("make {table}.{column} an identity column"),
        Op::DropIdentity { table, column } => format!("drop identity of {table}.{column}"),
        Op::AddConstraint { table, constraint } => format!("add constraint {} on {table}", constraint.name()),
        Op::DropConstraint { table, name } => format!("drop constraint {name} on {table}"),
        Op::RenameConstraint { table, from, to } => format!("rename constraint {from} on {table} to {to}"),
        Op::CreateIndex { table, index } => format!("create index {} on {table}", index.name),
        Op::DropIndex { name } => format!("drop index {name}"),
        Op::RenameIndex { from, to } => format!("rename index {from} to {to}"),
        Op::CreateTrigger { table, trigger } => format!("create trigger {} on {table}", trigger.name),
        Op::DropTrigger { table, name } => format!("drop trigger {name} on {table}"),
        Op::CommentOnTable { table, .. } => format!("comment on table {table}"),
        Op::CommentOnColumn { table, column, .. } => format!("comment on column {table}.{column}"),
    }
}
